#!/bin/bash

## Files and cmd
FILE="$HOME/.cache/eww_launch.xyz"
EWW="$HOME/Gits/eww/target/release/eww -c $HOME/.config/eww/bar"

## Monitor Name
MONITOR_NAME="eDP-1"

## Run eww daemon if not running already
if ! pgrep -x "eww" > /dev/null; then
    ${EWW} daemon
    sleep 1
fi

## Open widgets
run_eww() {
    ${EWW} open-many bar
}

## Set top_padding for the monitor
set_top_padding() {
    hyprctl monitors set "$MONITOR_NAME" top_padding 49
}

## Launch or close widgets accordingly
if [[ ! -f "$FILE" ]]; then
    touch "$FILE"
    run_eww
    set_top_padding
else
    ${EWW} close-all && killall eww
    rm "$FILE"
fi
